name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run-script build
        
    - name: Git Commit on Workflow
      uses: matheusalbino/git-commit@v1.1.0
      with:
        # Github Token
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Git user.name
        user-name: Github Actions - Git Commit
        # Git user.email
        user-email: github-actions-git-commit@users.noreply.github.com
        # Git message
        message: This a commit from Github Actions (auto-build)
        branch: master
