name: html5-qrcode build and distribute

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]  # (only run on one version since we are committing back to the repo (we could build against all node versions in a separate action
    
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run-script build
    
  git-commit:
    runs-on: ubuntu-latest
    needs: build
    
    strategy:
      matrix:
        node-version: [12.x]  # (only run on one version since we are committing back to the repo
    
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build to commit
      run: |
        npm install
        npm run-script build

    - name: Git Commit on Workflow
      uses: matheusalbino/git-commit@v1.1.0
      with:
        # Github Token
        github-token: ${{ secrets.GITHUB_TOKEN }}
#         # Git user.name
#         user-name: Github Actions - Git Commit
#         # Git user.email
#         user-email: github-actions-git-commit@users.noreply.github.com
        # Git message
        message: This a commit from Github Actions (auto-build)
        
        ### this is not recognizing changes to commit
#     - name: Git Auto Commit
#       # You may pin to the exact commit or the version.
#       # uses: stefanzweifel/git-auto-commit-action@5dd17c3b53a58c1cb5eaab903826abe94765ccd6
#       uses: stefanzweifel/git-auto-commit-action@v4.11.0
#       with:
#         # Commit message
#         commit_message: Apply automatic changes
#         commit_options: '--no-verify --signoff'
#         file_pattern: dist/html5-qrcode.min.js
#         # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
#         branch: ${{ github.head_ref }}
#         # Name used for the commit user
#         commit_user_name: GitHub Actions
#         # Email address used for the commit user
#         commit_user_email: actions@github.com
#         # Value used for the commit author. Defaults to the username of whoever triggered this workflow run.
#         commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        

